import Head from "next/head";
import React from "react";

function MainLayout({ children }: any) {
  return (
    <div>
      <Head>
        <title>Fake Store App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {children}
    </div>
  );
}

export default MainLayout;
