import Head from "next/head";
import Image from "next/image";
import { Button, ButtonGroup, Stack } from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fake Store App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Stack spacing={4} direction="row" align="center">
          <Button colorScheme="teal" size="xs">
            Button
          </Button>
          <Button colorScheme="teal" size="sm">
            Button
          </Button>
          <Button colorScheme="teal" size="md">
            Button
          </Button>
          <Button colorScheme="teal" size="lg">
            Button
          </Button>
        </Stack>
      </main>

      <footer></footer>
    </div>
  );
}
